const musicLibrary = [
        { title: 'Nikes', artist: 'Frank Ocean', path: 'assets/music/Blonde/Nikes.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Ivy', artist: 'Frank Ocean', path: 'assets/music/Blonde/Ivy.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Pink + White', artist: 'Frank Ocean', path: 'assets/music/Blonde/Pink + White.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Be Yourself', artist: 'Frank Ocean', path: 'assets/music/Blonde/Be Yourself.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Solo', artist: 'Frank Ocean', path: 'assets/music/Blonde/Solo.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Skyline To', artist: 'Frank Ocean', path: 'assets/music/Blonde/Skyline To.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Self Control', artist: 'Frank Ocean', path: 'assets/music/Blonde/Self Control.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Good Guy', artist: 'Frank Ocean', path: 'assets/music/Blonde/Good Guy.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Nights', artist: 'Frank Ocean', path: 'assets/music/Blonde/Nights.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Solo (Reprise)', artist: 'Frank Ocean', path: 'assets/music/Blonde/Solo (Reprise).mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Pretty Sweet', artist: 'Frank Ocean', path: 'assets/music/Blonde/Pretty Sweet.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Facebook Story', artist: 'Frank Ocean', path: 'assets/music/Blonde/Facebook Story.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Close to You', artist: 'Frank Ocean', path: 'assets/music/Blonde/Close to You.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'White Ferrari', artist: 'Frank Ocean', path: 'assets/music/Blonde/White Ferrari.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Seigfried', artist: 'Frank Ocean', path: 'assets/music/Blonde/Seigfried.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Godspeed', artist: 'Frank Ocean', path: 'assets/music/Blonde/Godspeed.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },
        { title: 'Futura Free', artist: 'Frank Ocean', path: 'assets/music/Blonde/Futura Free.mp3', cover: 'assets/covers/Blonde.png', album: 'Blonde' },

        { title: 'BLOOD.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/BLOOD.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'DNA.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/DNA.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'YAH.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/YAH.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'ELEMENT.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/ELEMENT.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'FEEL.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/FEEL.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'LOYALTY.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/LOYALTY.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'PRIDE.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/PRIDE.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'HUMBLE.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/HUMBLE.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'LUST.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/LUST.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'LOVE.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/LOVE.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'XXX.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/XXX.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'FEAR.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/FEAR.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'GOD.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/GOD.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },
        { title: 'DUCKWORTH.', artist: 'Kendrick Lamar', path: 'assets/music/DAMN/DUCKWORTH.mp3', cover: 'assets/covers/DAMN..png', album: 'DAMN.' },


        { title: 'Wesley’s Theory', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/Wesleys Theory.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'King Kunta', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/King Kunta.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'Institutionalized', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/Institutionalized.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'These Walls', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/These Walls.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'u', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/u.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'Alright', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/Alright.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'Momma', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/Momma.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'Hood Politics', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/Hood Politics.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'How Much a Dollar Cost', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/How Much A Dollar Cost.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'Complexion (A Zulu Love)', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/Complexion.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'The Blacker the Berry', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/The Blacker The Berry.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'You Ain’t Gotta Lie (Momma Said)', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/You Aint Gotta Lie.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'i', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/i.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        { title: 'Mortal Man', artist: 'Kendrick Lamar', path: 'assets/music/TPAB/Mortal Man.mp3', cover: 'assets/covers/TPAB.png', album: 'To Pimp a Butterfly' },
        
       
        { title: 'United In Grief', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/United In Grief.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'N95', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/N95.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Worldwide Steppers', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Worldwide Steppers.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Die Hard', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Die Hard.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Father Time', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Father Time.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Rich Spirit', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Rich Spirit.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'We Cry Together', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/We Cry Together.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Purple Hearts', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Purple Hearts.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Count Me Out', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Count Me Out.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Crown', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Crown.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Silent Hill', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Silent Hill.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Savior (Interlude)', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Savior - Interlude.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Savior', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Savior.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Auntie Diaries', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Auntie Diaries.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Mr. Morale', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Mr. Morale.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Mother I Sober', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Mother I Sober.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },
        { title: 'Mirror', artist: 'Kendrick Lamar', path: 'assets/music/MrMorale/Mirror.mp3', cover: 'assets/covers/MrMorale.png', album: 'Mr. Morale & The Big Steppers' },

        
        { title: 'Sherane a.k.a Master Splinter’s Daughter', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/Sherane.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'Bitch, Don’t Kill My Vibe', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/Bitch, Dont Kill My Vibe.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'Backseat Freestyle', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/Backseat Freestyle.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'The Art of Peer Pressure', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/The Art of Peer Pressure.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'Money Trees', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/Money Trees.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'Poetic Justice', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/Poetic Justice.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'good kid', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/good kid.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'm.A.A.d city', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/m.A.A.d city.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'Swimming Pools (Drank)', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/Swimming Pools (Drank).mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'Sing About Me, I’m Dying of Thirst', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/SAMIDOT.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'Real', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/Real.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' },
        { title: 'Compton', artist: 'Kendrick Lamar', path: 'assets/music/GKMC/Compton.mp3', cover: 'assets/covers/GKMC.png', album: 'good kid, m.A.A.d city' }
        
        
];